name: 'JS Tests'
on:
  pull_request:
    paths:
      - 'common/src/resources/js/**'
      - 'common/src/resources/modules/**'
      - 'common/*.json'
      - 'common/*.js'
      - 'src/resources/js/**'
      - 'src/resources/modules/**'
      - 'package.json'
      - 'webpack.*.js'
      - 'jest.config.json'
      - 'jest.setup.js'
      - 'jsconfig.json'
      - '.github/workflows/tests-js.yml'
jobs:
  test:
    strategy:
      matrix:
        suite:
          - test
          - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout automation tools
        uses: actions/checkout@v2
        with:
          repository: moderntribe/tric
          ref: main
          path: tric
          fetch-depth: 1
      - name: Add tric to the PATH
        run: echo "::set-env name=PATH::${GITHUB_WORKSPACE}/tric:$PATH"
      - name: Set run_context() for tric
        run: echo "::set-env name=TRIC::1"
      - name: Start ssh-agent
        run: |
          mkdir -p "${HOME}/.ssh";
          ssh-agent -a /tmp/ssh_agent.sock;
      - name: Export SSH_AUTH_SOCK env var
        run: echo "::set-env name=SSH_AUTH_SOCK::/tmp/ssh_agent.sock"
      - name: tric use event-tickets
        run: |
          cd ${GITHUB_WORKSPACE}/..
          tric here
          tric interactive off
          tric build-prompt off
          tric debug on
          tric info
      - name: tric npm install for common
        run: |
          tric use event-tickets/common
          tric run npm install
      - name: Set up event-tickets
        run: tric use event-tickets
      - name: tric npm install
        run: tric npm install
      - name: Run JS test suite
        run: tric npm run ${{ matrix.suite }}
