name: 'JS Tests'
on:
  pull_request:
    paths:
      - 'common/src/resources/js/**'
      - 'common/src/resources/modules/**'
      - 'common/*.json'
      - 'common/*.js'
      - 'src/resources/js/**'
      - 'src/resources/modules/**'
      - 'package.json'
      - 'webpack.*.js'
      - 'jest.config.json'
      - 'jest.setup.js'
      - 'jsconfig.json'
      - '.github/workflows/tests-js.yml'
jobs:
  test:
    strategy:
      matrix:
        suite:
          - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Run JS test suite
        run: npm run ${{ matrix.suite }}
